# Generated by Django 2.1.7 on 2019-08-22 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iwansell', '0005_auto_20190814_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=200)),
                ('catch', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Channel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Comment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reply1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_t', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Reply')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reply1Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('reply1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Reply1')),
            ],
        ),
        migrations.CreateModel(
            name='Reply2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('reply1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Reply1')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reply2Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('reply2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Reply2')),
            ],
        ),
        migrations.CreateModel(
            name='Reply3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('reply2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Reply2')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reply3Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('reply3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Reply3')),
            ],
        ),
        migrations.CreateModel(
            name='Reply4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('reply3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Reply3')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reply4Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('reply4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Reply4')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Reply')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thread', models.TextField()),
                ('media', models.FileField(upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('campus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iwansell.Campus')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Channel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ThreadVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Account')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Thread')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientratereview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eshopratereview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ratereview',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='clientratereview',
            name='date',
        ),
        migrations.RemoveField(
            model_name='eshopratereview',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iwansell.Thread'),
        ),
    ]
